---
pipeline:
  name: tempAirTriple_egress
transform:
  image_pull_secrets:
  - battelleecology-quay-read-all-pull-secret
  image: quay.io/battelleecology/egress:7
  cmd:
  - /bin/bash
  stdin:
  - '#!/bin/bash'
  - python3 -m egress.egress.app --outputname tempAirTriple --dateindex 2 --locindex
    1
  env:
    OUT_PATH: /pfs/out
    LOG_LEVEL: INFO
output_branch: master
input:
  pfs:
    name: DATA_PATH
    repo: tempAirTriple_level1_group
    branch: master
    glob: /*/*/*
egress:
  URL: s3://int-omnipipe
standby: true

